### ISSUE TITLE
New example with social sign ins and `sign_in_module_2`

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished_example_apps#10]
We may need to deploy this one to our own VM rather than shinyapps.io to get the social sign ins to work properly.  Let's set it up to work properly with 3rd party cookies disabled.

**Comment by phoward38** [comment]
Should I use `polished_example_apps` as the URL path? So `apps.tychobra.com/polished_example_apps`?

**Comment by merlinoa** [comment]
no use "06_social_sign_in".  Also change the name on the "06_your_own_firebase_project" folder to "XX_your_own_firebase_project".  I am not sure if/where we are going to include this Firebase example.  We will definitely need to modify it before including it.

**Comment by phoward38** [comment]
Created branch `add/social_sign_in`

- [ ] Change directory name
- [ ] Deploy to Cloud Run

**Comment by merlinoa** [comment]
Slight change of plans.  We are going to make 2 examples:

 - "06_social_sign_in" will just use the standard "sign_in_module" and
 - "07_alt_sign_in_ui" will use "sign_in_module_2"

Both of the above examples will use Google and Microsoft sign in providers.  Make sure to do the setup to avoid the 3rd party cookie issue for the Google sign in.

**Comment by phoward38** [comment]
New examples deployed & DNS records to be added for custom domains in Cloud Run sent to @merlinoa in Slack

**Comment by merlinoa** [comment]
CNAME records have been added to the DNS.  Apps are live here:

https://examples.social-sign-in-1.tychobra.com
https://examples.social-sign-in-2.tychobra.com

We are all set here.  Closing this issue out.
