### ISSUE TITLE
Flexdashboard

### ISSUE THREAD

**Issue by ffalcolini** [Tychobra/polished_example_apps#11]
Hello!

I can't use Polished with flexdashboard (I'm trying with R Studio).
My Rmd application file in which folder should I put it?
In addition to the app key code and application name, do I need to do any other configuration?

Thank a lot!
Francesco

**Comment by merlinoa** [comment]
Hi @ffalcolini 

You need to put the html file that is generated from your Rmd in the "www" folder.  If you set up your app like this everything should work: https://github.com/Tychobra/polished_example_apps/tree/master/05_flex_dashboard

Make sure to call `shiny::runApp()` to run your app.  Also please install the latest development version of polished from GitHub using:

```
remotes::install_github("tychobra/polished")
```

Let me know if you have any issues.
