### ISSUE TITLE
Initial email invite isn't received

### ISSUE THREAD

**Issue by dcaud** [Tychobra/polished_example_apps#15]
I tried with a gmail and a yahoo account -- neither sent the initial invitation *until* I clicked "resend invite."

**Comment by merlinoa** [comment]
Hi @dcaud 

I just tested with the "03_no_invite_required" example app, and I did receive an email verification email after registering.  Is this the same app that you were using when you experienced the issue?  If not, can you provide more info?  Thanks

**Comment by dcaud** [comment]
Ah, I placed this issue in the wrong repo -- it wasn't a problem with the no_invite_required example app, but rather an app I created. However, I just added another email and the first email went through, so I'm not able to reproduce the issue. Feel free to close!
