### ISSUE TITLE
Flexdashboard

### ISSUE THREAD

**Issue by zjmarg** [Tychobra/polished_example_apps#16]
I am struggling to adapt the code provided to work with my flexdashboard. Currently, my flexdashboard is an interactive R markdown document that is being hosted by shinyapps.io and I have registered the dashboard as a "Shiny app" on the polished website. However, I am unsure of how to actually change my markdown document to utilize polished. Can you provide clarity on this?

**Comment by merlinoa** [comment]
You will need to create a shiny app with this file and folder structure: https://github.com/Tychobra/polished_example_apps/tree/master/05_flex_dashboard

Place the html document produced by the ".Rmd" in the "www/".

You can test running the app locally by running `shiny::runApp()`.  If polished is configured correctly, the app will open to the polished sign in page.

**Comment by zjmarg** [comment]
I see that's helpful! Do you know how to retrieve the html document  produced by the flexdashboard? I haven't done that yet. This is a great product and I appreciate your help.

**Comment by merlinoa** [comment]
Thanks! The html document is created by the Rmd when you knit the Rmd.  If you are using Rstudio, you can click this button to knit the Rmd: 
<img width="437" alt="Screen Shot 2021-01-04 at 5 12 29 PM" src="https://user-images.githubusercontent.com/4030554/103584903-311b1080-4eb0-11eb-81c7-e96c7fc9c6bb.png">


Once the html document is created, you can just copy and paste it into the "www" folder.

**Comment by merlinoa** [comment]
This issue is related to #17.  @zjmarg was attempting to use runtime shiny with polished.  Unfortunately polished does not currently support runtime shiny.

**Comment by merlinoa** [comment]
Polished now supports runtime shiny in Rmarkdown documents! Example app here: https://github.com/Tychobra/polished_example_apps/tree/master/09_rmarkdown

**Comment by zjmarg** [comment]
Awesome thank you!
