### ISSUE TITLE
{"error":"API key not provided in HTTP_AUTHORIZATION header"}

### ISSUE THREAD

**Issue by agronomofiorentini** [Tychobra/polished_example_apps#20]
Dear creators,
I would like to use your authentication service in order to secure my plumber api, but i have a problem.

When i run the plumber.R file in the viewer pane it says to me

```
{"error":"API key not provided in HTTP_AUTHORIZATION header"}
```

<img width="408" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/209639390-f914e7e4-00b0-4975-9a1c-9331014258c2.png">

And the follow is the entire R code used to develop the Plumber api

```
library(plumber)
library(polished)
library(future)
library(readxl)
library(tidyverse)

polished::polished_config(
  api_key = "aaaaaaabbbbbbb",
  app_name = "aaaaaaabbbbbb"
)

#' @filter auth
polished::auth_filter("basic")

#* @tag Phytopharmaceuticals
#* @param product_name:string Phytopharmaceutical product name
#* @post /phytopharmaceuticals
#* @serializer json
function(product_name){

  future::future({

    data <- read_excel("C_17_dataset_6_download_itemDownload0_upFile.xlsx")

    data$PRODOTTO<-tolower(data$PRODOTTO)

    data %>%
      dplyr::filter(PRODOTTO==product_name)
  })

}
```

What's wrong with my code?

**Comment by merlinoa** [comment]
Hi.  Thanks for trying out polished for plumber.  Can you include an example of the request?  Send me an email if you want to set up a screenshare to do a debug session.

**Comment by agronomofiorentini** [comment]
Hi @merlinoa,
I have tried to make a post request to the api by using the following code:

```
api_url <- "http://localhost:5551/phytopharmaceuticals?product_name=ENOVIT"

r <- httr::POST(
  api_url,
  httr::authenticate(
    user = "aaaaaa@gmail.com",
    password = "aaaaaaa"
  )
)
```

and this is the api status that i have got

```
httr::status_code(r)
>200
```

and this is the results of the query, which is `NULL`

```
rc <- httr::content(r)

unlist(rc)
>NULL
```

for the screenshare session, i am in and happy to collaborate, i will send you an email.

**Comment by agronomofiorentini** [comment]
Any news about this issue?

**Comment by merlinoa** [comment]
I think this should be fixed now with the latest update that was just pushed to GitHub. Please let me know if you are still seeing issues.  Thanks for the issue report

**Comment by merlinoa** [comment]
instruction to update and resolve this bug for reference/doc purposes: 

Install latest version of polished with:  `remotes::install_github("tychobra/polished")`

then restart your R session, and you should be good to go.

**Comment by agronomofiorentini** [comment]
Hi i have installed the polished package from github, And I ran the code reported earlier but I get the same error.

**Comment by merlinoa** [comment]
Can you try again now with the latest version?

**Comment by agronomofiorentini** [comment]
The post request works perfectly, while the documentation doens't render.

It is possible also to render well the documentation by using the polished authentication into plumber?

<img width="338" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/213212490-ba46f29a-d181-4f2d-9ddd-04dd7d6852ab.png">

**Comment by merlinoa** [comment]
I just added `add_auth_to_spec` function to polished which you can use to add basic and cookie based auth to swagger: https://github.com/Tychobra/polished/blob/777edae06e842fa41c892ba264b719901578ed01/R/auth_filter.R#L250

I updated the plumber example to use this function: https://github.com/Tychobra/polished_example_apps/blob/94dd1328016c12408fe05d0fe1dabbd7f5015583/11_plumber/api/00_start.R#L9

**Comment by agronomofiorentini** [comment]
I have installed the latest version of polished by using devtools but actually when i am adding the  polished::add_auth_to_spec() the console give me the follow error

`Error: 'add_auth_to_spec' is not an exported object from 'namespace:polished'`

Sorry to bother you.

This is my plumber file

```
library(plumber)
library(polished)
library(future)
library(readxl)
library(tidyverse)

polished::polished_config(
  api_key = "aaaaaa",
  app_name = "bbbbbb"
)

#' @filter auth
polished::auth_filter("basic")

#* @tag Phytopharmaceuticals
#* This endpoint allows you to get all the information about authorized and unauthorized plant protection products
#* @param product_name:string Phytopharmaceutical product name (example: enovit)
#* @post /phytopharmaceuticals
#* @serializer json
function(product_name){

  future::future({

    data <- read_excel("C_17_dataset_6_download_itemDownload0_upFile.xlsx")

    #data$

    #data$PRODOTTO<-tolower(data$PRODOTTO)

    data %>%
      dplyr::filter(PRODOTTO==product_name)
  })

}

```


this is the file to run the plumber api

```
library(plumber)
library(redoc)
library(rapidoc)

plumb(file = "plumber.R", dir = ".") %>%
  plumber::pr_set_docs("swagger") %>%
  pr_set_api_spec(add_auth_to_spec()) %>%
  pr_run(port=8000)
```

but still have the same problem, the documentation doesn't render

**Comment by agronomofiorentini** [comment]
Dear @merlinoa,
I have restarted the r session and use the polished_example_apps and now the UI of the API is working.

<img width="668" alt="Screenshot_1" src="https://user-images.githubusercontent.com/66969646/213382751-abcbbb32-5ec3-4d6b-80cf-7ff63b3826f0.png">

This is the code to run the plumber code

```
library(plumber)
library(polished)

#* @plumber
function(pr) {
  pr %>%
    # optionally add auth to the openapi spec so that you can use swagger with the auth filter
    pr_set_api_spec(polished::add_auth_to_spec()) %>%
    pr_mount("/v1", plumb("./plumber_polished_auth_2.R")) %>%
    plumber::pr_set_docs("swagger")
}
```

and the plumber_polished_auth_2.R is the following

```
library(plumber)
library(polished)
library(future)
library(readxl)
library(tidyverse)

polished::polished_config(
  api_key = "aaaaaa",
  app_name = "bbbbb"
)

#' @filter auth
polished::auth_filter("basic")

#* @tag Phytopharmaceuticals
#* This endpoint allows you to get all the information about authorized and unauthorized plant protection products
#* @param product_name:string Phytopharmaceutical product name (example: enovit)
#* @post /phytopharmaceuticals
#* @serializer json
function(product_name){

  future::future({

    data <- read_excel("C_17_dataset_6_download_itemDownload0_upFile.xlsx")

    #data$

    #data$PRODOTTO<-tolower(data$PRODOTTO)

    data %>%
      dplyr::filter(PRODOTTO==product_name)
  })

}
```

But the problem now arises when I try to make the post request.

This is the code to make the POST request

```
library(httr)
library(tidyverse)
library(jsonlite)

api_url <- "http://localhost:8665/phytopharmaceuticals?product_name=ENOVIT"

r <- httr::POST(
  api_url,
  httr::authenticate(
    user = "aaaa",
    password = "bbbbb"
  )
)

httr::status_code(r)
[1] 404

cont <- content(r, as = "text", type = "application/json")
jsonlite::fromJSON(cont) %>% as.data.frame

error
1 404 - Resource Not Found

rc <- httr::content(r)

unlist(rc)
error 
"404 - Resource Not Found" 
```

**Comment by merlinoa** [comment]
the pr_mount adds a "v1/" prefix to your endpoint urls.  i.e. the above post is now:  "http://localhost:8665/v1/phytopharmaceuticals?product_name=ENOVIT"

You can change the pr_mount to remove the v1, but IMO it is good practice to include the version in the url.

**Comment by agronomofiorentini** [comment]
dear @merlinoa it is working perfectly now.

It is always a typo
