### ISSUE TITLE
create mp4 video for first example app

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished_example_apps#8]
@nickmerl Please make a short mp4 videos of the first example app in action.  

It should only be around 5 seconds.  Just show the user sign in and go to the app.  We may want to add subtitles. 

If the videos work well we will use them in the new "examples" page that we are adding to the polished.tech website.  If they are overkill we will just use images.  This first video will just be to test out whether or not we want to use videos.  Let @RichardHHill know when the video is ready and he can add it to the examples page for us to test is out.

**Comment by nickmerl** [comment]
do I need a config.yml for this?

**Comment by nickmerl** [comment]
never-mind I am just going to set one up on polished.tech

**Comment by merlinoa** [comment]
@nickmerl the apps are live on shinyapps.io.  You can sign in using the instructions in the readme.  Use the demo@tychobra email address from the readme for the videos.

**Comment by merlinoa** [comment]
these are done
