### ISSUE TITLE
apexcharter time series range slider not working when deployed

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/polished_example_apps#9]
Check out the chart in the bottom right for this app: https://tychobra.shinyapps.io/04_interest_rate_walk 

The date range slider that goes below the chart is missing.  It works fine when running the app locally.  I know this happened before as well.  

@phoward38 Do you remember what the issue was?

**Comment by phoward38** [comment]
@merlinoa I was never able to determine the source of the error. I deployed their [brush chart example](https://dreamrs.github.io/apexcharter/articles/sync-charts.html) to a VM instance and the same error occurred.

**Comment by merlinoa** [comment]
ok let's forget about it

**Comment by phoward38** [comment]
@merlinoa Added workaround w/ b7b9f66c218a6a2ea817d80aa0bfe8bf898177ba

**Comment by merlinoa** [comment]
sweet! redeployed
